version: "3"
services:
  client:
    build: .
    image: spa_vue-2_js_hello-world:starter
    container_name: spa_vue-2_js_hello-world_starter
    ports:
      - 4040:4040
      - 6060:6060
    env_file:
      - .env
